remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: true
  week: false
  24 hours: true

positions:
  - Software Tester
  - Software Developer
  - Data Scientist

locations:
  - England
  - London
  - Manchester
  - Bristol
  - Newcastle
  - Leeds
  - Edinburgh
  - Glasgow
  - Cardiff
  - Birmingham
  - Liverpool
  - Leeds
  - Newcastle
  - Edinburgh
  - Glasgow
  - Cardiff
  - Birmingham
  - Liverpool
  - London
  - Manchester
  - Bristol
  - Newcastle
  - Leeds
  - Edinburgh
  - Glasgow
  - Cardiff
  - Birmingham
  - Liverpool
  - Remote

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:
